### ISSUE TITLE
Not able to get working

### ISSUE THREAD

**Issue by nolastan** [archana-s/postcss-speech-bubble#1]
Is this still working for folks? I'm calling it in my compiler just like all my other postcss plugins, but my output still contains the `bubble` attribute and not the compiled output I'd expect from the plugin. No errors though.

**Comment by archana-coursera** [comment]
Thanks for logging the bug Stan. I will take a look at it today.

**Comment by archana-s** [comment]
I will take a look at it today. thanks for logging the bug.

**Comment by archana-s** [comment]
@nolastan I am able to get it running locally. 
Here's my gulpfile just for reference: 

```
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var flexbox = require('postcss-flexbox'); //postcss-flexbox plugin
var popover = require('postcss-speech-bubble'); 
var autoprefixer = require('autoprefixer');

gulp.task('process-css', function() {
  var processors = [
    flexbox, popover, autoprefixer
  ];
  return gulp.src('./src/*.css')
    .pipe(postcss(processors))
    .pipe(gulp.dest('./dist'));
});
```

Are you able to get other plugins running? Let me know if you want help debugging it together.
